pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'docker.io/mulaudzimk/myapp' // DockerHub username/repo
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the repository containing the Python app and Dockerfile
                git branch: 'main', url: 'https://github.com/Mulaudzi-MK/terraform-jenkins-pipeline/edit/main/Docker/Jenkinsfile.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image for the Python app
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Run the Docker container from the built image
                    sh 'docker run -d -p 3500:3500 $DOCKER_IMAGE'
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                script {
                    // Login to DockerHub
                    sh '''
                    echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
                    '''
                    // Push the Docker image to DockerHub
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image built, run, and pushed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
